import headshot from "../images/headshot.png";
import alina from "../images/headshots/alina_headshot.webp";
import alix from "../images/headshots/alix_headshot.webp";
import anvita from "../images/headshots/anvita_headshot.webp";
import arya from "../images/headshots/arya_headshot.webp";
import jenny from "../images/headshots/jenny_headshot.webp";
import lily from "../images/headshots/lily_headshot.webp";
import rivkah from "../images/headshots/rivkah_headshot.webp";
import victoria from "../images/headshots/victoria_headshot.webp";
import yifei from "../images/headshots/yifei_headshot.webp";
import sruti from "../images/headshots/sruti_headshot.webp";
import chloe from "../images/headshots/chloe_headshot.webp";
import akshita from "../images/headshots/akshita_headshot.webp";
import stephanie from "../images/headshots/stephanie_headshot.webp";
import nora from "../images/headshots/nora_headshot.webp";
import caroline from "../images/headshots/caroline_headshot.webp";

export const execBoardData = [
        {
            name: "Victoria Li",
            photo: victoria,
            position: "Co-President",
            year: "Master's",
            major: "Education Studies & Social Policy",
            hometown: "Highland Park, NJ",
            linkedin: "https://www.linkedin.com/in/victoria-li-a6a366257/",
            email: "victoria.li@nyu.edu",
        },
        {
            name: "Sruti Jonnalagadda",
            photo: sruti,
            position: "Co-President",
            year: "Senior",
            major: "Economics & Math",
            hometown: "Pleasanton, California",
            linkedin: "https://www.linkedin.com/in/srutij/",
            email: "sj3721@nyu.edu",
        },
        {
            name: "Akshita Kannan",
            photo: akshita,
            position: "Vice President",
            year: "Junior",
            major: "Economics",
            hometown: "North Royalton, OH",
            linkedin: "https://www.linkedin.com/in/akshita-kannan/",
            email: "ak10524@nyu.edu",
        },
        {
            name: "Nora Cummins",
            photo: nora,
            position: "Director of Prof. Development",
            year: "Senior",
            major: "Economics",
            hometown: "Louisville, KY",
            linkedin: "https://www.linkedin.com/in/norajcummins/",
            email: "njc9333@nyu.edu",
        },
        {
            name: "Chloe Kindangen",
            photo: chloe,
            position: "Director of Media",
            year: "Junior",
            major: "Business",
            hometown: "Jakarta, Indonesia",
            linkedin: "https://www.linkedin.com/in/chloekindangen/",
            email: "ck3469@stern.nyu.edu",
        },
        {
            name: "Yi-Fei Zhao",
            photo: yifei,
            position: "Director of Technology",
            year: "Junior",
            major: "Stats & CS",
            hometown: "Pittsburgh, PA",
            linkedin: "https://www.linkedin.com/in/yi-fei-zhao/",
            email: "yi-fei.zhao@stern.nyu.edu",
        },
    ];

    export const pmData = [
        {
            name: "Stephanie Tinco",
            photo: stephanie,
            position: "Project Manager",
            year: "Senior",
            major: "Economics",
            hometown: "Bronx, New York",
            linkedin: "https://www.linkedin.com/in/stephanie-tinco/",
            email: "skt9886@nyu.edu",
        },
        {
            name: "Chloe Kindangen",
            photo: chloe,
            position: "Project Manager",
            year: "Junior",
            major: "Economics",
            hometown: "Hong Kong",
            linkedin: "https://www.linkedin.com/in/chloe-kindangen/",
            email: "ck3469@stern.nyu.edu",
        },
        {
            name: "Leon Dang",
            photo: headshot,
            position: "Project Manager",
            year: "Junior",
            major: "Finance & Data Science",
            hometown: "Chester Springs, PA",
            linkedin: "https://www.linkedin.com/in/leon-dang/",
            email: "lxd2003@nyu.edu",
        },
        {
            name: "Alex Li",
            photo: headshot,
            position: "Project Manager",
            year: "Sophomore",
            major: "Finance & Data Science",
            hometown: "San Jose, California",
            linkedin: "https://www.linkedin.com/in/alexli254/",
            email: "alexli@stern.nyu.edu",
        },
    ];

    export const seniorConsultantsData = [
        {
            name: "Arya Nadella",
            photo: arya,
            position: "Consultant",
            year: "Junior",
            major: "Maths & Economics",
            hometown: "Hyderabad, India",
            linkedin: "https://www.linkedin.com/in/arya-nadella-3a4b33230/",
            email: "an4057@nyu.edu",
        },
        {
            name: "Lily Liang",
            photo: lily,
            position: "Consultant",
            year: "Sophomore",
            major: "Data Science & Management",
            hometown: "Toronto, Canada",
            linkedin: "https://www.linkedin.com/in/lily-liang1109/",
            email: "jl15890@stern.nyu.edu",
        },
        {
            name: "Anvita Gurumurthy",
            photo: anvita,
            position: "Consultant",
            year: "Junior",
            major: "Finance & Management",
            hometown: "Basking Ridge, NJ",
            linkedin: "https://www.linkedin.com/in/anvita-gurumurthy/",
            email: "ag9696@stern.nyu.edu",
        },
        {
            name: "Caroline Chan",
            photo: caroline,
            position: "Consultant",
            year: "Junior",
            major: "Economics & Data Science",
            hometown: "San Francisco, CA",
            linkedin: "https://www.linkedin.com/in/caroline-chan/",
            email: "caroline.chan@stern.nyu.edu",
        },
        {
            name: "Jenny Kim",
            photo: jenny,
            position: "Consultant",
            year: "Junior",
            major: "Economics & Strategic Thinking",
            hometown: "Seoul, South Korea",
            linkedin: "https://www.linkedin.com/",
            email: "jennykim@nyu.edu",
        },
        {
            name: "Rivkah-Esther Henig",
            photo: rivkah,
            position: "Consultant",
            year: "Junior",
            major: "Finance & Accounting",
            hometown: "Brooklyn, NY",
            linkedin: "https://www.linkedin.com/in/rivkah-h-00ba08304/",
            email: "rh3801@stern.nyu.edu",
        },
        {
            name: "Alina Panteleeva",
            photo: alina,
            position: "Consultant",
            year: "Junior",
            major: "Math & Economics",
            hometown: "Moscow, Russia",
            linkedin: "https://www.linkedin.com/in/alina-panteleeva/",
            email: "ap8383@nyu.edu",
        },
        {
            name: "Alix Yoon",
            photo: alix,
            position: "Consultant",
            year: "Junior",
            major: "Finance & Data Science",
            hometown: "Fort Lee, New Jersey",
            linkedin: "https://www.linkedin.com/in/jy72/",
            email: "joowon.yoon@stern.nyu.edu",
        },
    ];

    export const consultantsData = [
        {
            name: "Aarush Mathur",
            photo: headshot,
            position: "Consultant",
            year: "Junior",
            major: "Math & Economics",
            hometown: "Delhi, India",
            linkedin: "https://www.linkedin.com/in/aarushmathur/",
            email: "",
        },
        {
            name: "Anthony Lease",
            photo: headshot,
            position: "Consultant",
            year: "Sophomore",
            major: "Finance & Real Estate",
            hometown: "Newburgh, New York",
            linkedin: "www.linkedin.com/in/anthony-lease",
            email: "",
        },
        {
            name: "James Zhang",
            photo: headshot,
            position: "Consultant",
            year: "Junior",
            major: "Data Science & Math",
            hometown: "Irvine, CA",
            linkedin: "https://www.linkedin.com/in/jimmyzhang3858",
            email: "",
        },
        {
            name: "Nicole Zhao",
            photo: headshot,
            position: "Consultant",
            year: "Sophomore",
            major: "Finance & Management",
            hometown: "Vero Beach, Fl",
            linkedin: "https://www.linkedin.com/in/zhaonicole1",
            email: "",
        },
        {
            name: "Saaesha Bhimjiani",
            photo: headshot,
            position: "Consultant",
            year: "Junior",
            major: "Business & Political Economy, Philosophy",
            hometown: "Cary, NC",
            linkedin: "https://www.linkedin.com/in/saaesha-bhimjiani/",
            email: "",
        },
        {
            name: "David Zhang",
            photo: headshot,
            position: "Consultant",
            year: "Sophomore",
            major: "Economics & Chemistry",
            hometown: "Columbus, IN",
            linkedin: "https://www.linkedin.com/in/david-zhang-183740273/",
            email: "",
        },
        {
            name: "Sheng Huang",
            photo: headshot,
            position: "Consultant",
            year: "Sophomore",
            major: "Business, Technology, Entrepreneurship",
            hometown: "Guangdong, China; Manhattan, NY",
            linkedin: "https://www.linkedin.com/in/sheng-huang-a42a06217/ ",
            email: "",
        },
        {
            name:"Manya Bahl",
            photo: headshot,
            position: "Consultant",
            year: "Sophomore",
            major: "Economics",
            hometown: "Singapore, Singapore",
            linkedin: "www.linkedin.com/in/manya-bahl-262b42234",
            email: "",
        },
        {
            name: "Joaquin Lopez",
            photo: headshot,
            position: "Consultant",
            year: "Sophomore",
            major: "Public Policy & Economics",
            hometown: "Manila, Philippines",
            linkedin: "www.linkedin.com/in/joaquin-lopez-331323234",
            email: "",
        },
        {
            name: "Prashansa Gour",
            photo: headshot,
            position: "Consultant",
            year: "Junior",
            major: "Finance & Data Science",
            hometown: "Los Angeles, California",
            linkedin: "https://www.linkedin.com/in/prashansa-gour/",
            email: "",
        }
    ];